22 Feb 16
--Rerun jobs on akili and aruco errored again with
    p11-kit: couldn't open config file: /etc/pkcs11/modules/gnome-keyring-module: Too many open files
    p11-kit: couldn't open config file: /etc/pkcs11/pkcs11.conf: Too many open files
    >>Error: Illegal digit(s) in integer: [p]
  Researching error to see how to fix.

--Looks like the program is trying to collect too many tubes and runs out of
  file handles--it's trying to get 50 tubes every 10 frames, but never reaches
  the end of either video (both died after printing frame 810).  Found that I
  call ffmpeg-open-video in
  get-medianflow-tube-from-starting-frame-and-proposal-box, but then never call
  ffmpeg-close-video.  Added the close call.  Also going to try getting slightly
  fewer (40) tubes every 10th frame, since the video gets opened once for every
  proposal box that generates a tube.  But keeping the output dir name with 50
  to keep it the same as the others.  Restarting jobs on akili and aruco at
  0915.

--Based on email from Jeff, moved akili and aruco jobs to istihbarat and wywiad
  at 0935.  Not sure how long those jobs will take on an 8-core server.

--Working on alignment of frames to phrases.  Starting with floorplan-1 since
  the two still-running tube generation jobs are both in floorplan-0. **REMEMBER
  that for phrases that use towards/away-from, ONLY use the frames where the
  robot is moving--will get bad scores if robot does not have a velocity.

--Noticed that for some runs, there are fewer frame-poses than frames; I think
  that the functions that use frame-poses (such as
  raw-tube-with-score-and-pose-list->world-corners-list and
  get-noun-preposition-paths) deal with this already.